# Initial Data Inspection Fraud Data

**Purpose:** Quickly get an understanding of the dataset's structure, types of variables, and initial data quality.

**Tasks:**
1. Load the dataset and check basic information.
2. Inspect first few rows (`head()`, `tail()`) to get an overview of the data.
3. Check data types for each feature (e.g., numerical, categorical).
4. Check the shape of the dataset: rows, columns.

In [21]:
import os
import json
import pandas as pd

In [2]:
df = pd.read_csv(r"D:\Doccuments\GitHub\End-to-End-MLOps-Pipeline\data\raw\fraud test.csv")
df.shape

(555719, 23)

In [3]:
df.columns

Index(['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category',
       'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip',
       'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time',
       'merch_lat', 'merch_long', 'is_fraud'],
      dtype='object')

In [4]:
data = df[df.columns[1:]].copy()
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555719 entries, 0 to 555718
Data columns (total 22 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   trans_date_trans_time  555719 non-null  object
 1   cc_num                 555719 non-null  float64
 2   merchant               555719 non-null  object
 3   category               555719 non-null  object
 4   amt                    555719 non-null  float64
 5   first                  555719 non-null  object
 6   last                   555719 non-null  object
 7   gender                 555719 non-null  object
 8   street                 555719 non-null  object
 9   city                   555719 non-null  object
 10  state                  555719 non-null  object
 11  zip                    555719 non-null  int64
 12  lat                    555719 non-null  float64
 13  long                   555719 non-null  float64
 14  city_pop               555719 non-null  int64
 15  job                    555719 non-null  object
 16  dob                    555719 non-null  object
 17  trans_num              555719 non-null  object
 18  unix_time              555719 non-null  int64
 19  merch_lat              555719 non-null  float64
 20  merch_long             555719 non-null  float64
 21  is_fraud               555719 non-null  int64
dtypes: float64(6), int64(4), object(12)
memory usage: 93.3+ MB

## Dataset Columns Description

| Column               | Description                                                                 |
|---------------------|-----------------------------------------------------------------------------|
| Trans_date_trans_time | Timestamp of the transaction (date and time).                              |
| Cc_num              | Unique customer identification number.                                     |
| Merchant            | The merchant involved in the transaction.                                  |
| Category            | Transaction type (e.g., personal, childcare).                              |
| Amt                 | Transaction amount.                                                         |
| First               | Cardholder's first name.                                                    |
| Last                | Cardholder's last name.                                                     |
| Gender              | Cardholder's gender.                                                        |
| Street              | Cardholder's street address.                                                |
| City                | Cardholder's city of residence.                                             |
| State               | Cardholder's state of residence.                                            |
| Zip                 | Cardholder's zip code.                                                      |
| Lat                 | Latitude of cardholder's location.                                          |
| Long                | Longitude of cardholder's location.                                         |
| City_pop            | Population of the cardholder's city.                                        |
| Job                 | Cardholder's job title.                                                     |
| Dob                 | Cardholder's date of birth.                                                 |
| Trans_num           | Unique transaction identifier.                                              |
| Unix_time           | Transaction timestamp (Unix format).                                        |
| Merch_lat           | Merchant's location (latitude).                                             |
| Merch_long          | Merchant's location (longitude).                                            |
| Is_fraud            | Fraudulent transaction indicator (1 = fraud, 0 = legitimate).              |

In [5]:
data.head()

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,21/06/2020 12:14,2.291160e+15,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,Columbia,...,33.9659,-80.9355,333497,Mechanical engineer,19/03/1968,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,21/06/2020 12:14,3.573030e+15,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,Altonah,...,40.3207,-110.4360,302,"Sales professional, IT",17/01/1990,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,21/06/2020 12:14,3.598220e+15,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,Bellmore,...,40.6729,-73.5365,34496,"Librarian, public",21/10/1970,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,21/06/2020 12:15,3.591920e+15,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,Titusville,...,28.5697,-80.8191,54767,Set designer,25/07/1987,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,21/06/2020 12:15,3.526830e+15,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,Falmouth,...,44.2529,-85.0170,1126,Furniture designer,06/07/1955,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0

In [30]:
# getiing numerical datatypes
num_cols = data.select_dtypes('number').columns.tolist()
data[num_cols].head()

,cc_num,amt,zip,lat,long,city_pop,unix_time,merch_lat,merch_long,is_fraud
0,2.291160e+15,2.86,29209,33.9659,-80.9355,333497,1371816865,33.986391,-81.200714,0
1,3.573030e+15,29.84,84002,40.3207,-110.4360,302,1371816873,39.450498,-109.960431,0
2,3.598220e+15,41.28,11710,40.6729,-73.5365,34496,1371816893,40.495810,-74.196111,0
3,3.591920e+15,60.05,32780,28.5697,-80.8191,54767,1371816915,28.812398,-80.883061,0
4,3.526830e+15,3.19,49632,44.2529,-85.0170,1126,1371816917,44.959148,-85.884734,0

In [31]:
cat_cols = data.drop(columns=num_cols).columns.tolist()
cat_cols = [col for col in cat_cols if col not in ['trans_date_trans_time','dob']]
data[cat_cols].head()

,merchant,category,first,last,gender,street,city,state,job,trans_num
0,fraud_Kirlin and Sons,personal_care,Jeff,Elliott,M,351 Darlene Green,Columbia,SC,Mechanical engineer,2da90c7d74bd46a0caf3777415b3ebd3
1,fraud_Sporer-Keebler,personal_care,Joanne,Williams,F,3638 Marsh Union,Altonah,UT,"Sales professional, IT",324cc204407e99f51b0d6ca0055005e7
2,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,Ashley,Lopez,F,9333 Valentine Point,Bellmore,NY,"Librarian, public",c81755dbbbea9d5c77f094348a7579be
3,fraud_Haley Group,misc_pos,Brian,Williams,M,32941 Krystal Mill Apt. 552,Titusville,FL,Set designer,2159175b9efe66dc301f149d3d5abf8c
4,fraud_Johnston-Casper,travel,Nathan,Massey,M,5783 Evan Roads Apt. 465,Falmouth,MI,Furniture designer,57ff021bd3f328f8738bb535c302a31b

In [10]:
data[['trans_date_trans_time','dob']].head()

  trans_date_trans_time         dob
0      21/06/2020 12:14  19/03/1968
1      21/06/2020 12:14  17/01/1990
2      21/06/2020 12:14  21/10/1970
3      21/06/2020 12:15  25/07/1987
4      21/06/2020 12:15  06/07/1955

In [11]:
time_cols = ['trans_date_trans_time','dob']

In [28]:
file_path = r"D:\Doccuments\GitHub\End-to-End-MLOps-Pipeline\notebooks\metadata\Credit_cols_classified.json"
os.makedirs(os.path.dirname(file_path), exist_ok=True)
with open(file_path, 'w') as file:
    json.dump({"num_cols":num_cols,"cat_cols":cat_cols,"time_cols":time_cols},file,indent=4)